name: PR Check

on:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
